<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <ApplicationId>com.xershade.reoria.client.android</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>0.1.0</ApplicationDisplayVersion>
    <NoWarn>XA0101;CS0618</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <Import Project="../../Build/Reoria.Common.props" />
  <Import Project="../../Build/Reoria.Engine.DependencyInjection.props" />
  <Import Project="../../Build/MonoGame.props" />
  <Import Project="../../Build/LiteNetLib.props" />

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="**\testhost.exe" />
    <None Remove="**\testhost.dll" />
    <None Remove="**\appsettings.json" />
    <None Remove="**\libCoverageInstrumentationMethod.so" />
    <None Remove="**\libInstrumentationEngine.so" />
  </ItemGroup>

  <Import Project="..\..\Source\Client\Reoria.Client.Assets\Reoria.Client.Assets.projitems" Label="Shared" />
  <Import Project="..\..\Source\Client\Reoria.Client.Core\Reoria.Client.Core.projitems" Label="Shared" />
  <Import Project="..\..\Source\Client\Reoria.Client.Network\Reoria.Client.Network.projitems" Label="Shared" />
  <Import Project="..\..\Source\Engine\Reoria.Engine.Application\Reoria.Engine.Application.projitems" Label="Shared" />
  <Import Project="..\..\Source\Engine\Reoria.Engine.Network\Reoria.Engine.Network.projitems" Label="Shared" />
  <Import Project="..\..\Source\Game\Reoria.Game.Entities\Reoria.Game.Entities.projitems" Label="Shared" />
  <Import Project="..\..\Source\Client\Reoria.Client.Entities\Reoria.Client.Entities.projitems" Label="Shared" />
  <Import Project="..\..\Source\Engine\Reoria.Engine.Core\Reoria.Engine.Core.projitems" Label="Shared" />

  <ItemGroup>
    <AndroidAsset Include="$(SolutionDir)\**\appsettings*.json" Exclude="$(SolutionDir)\**\Bin\**;$(SolutionDir)\**\obj\**;$(SolutionDir)\**\.git\**">
        <Link>Assets\%(Filename)%(Extension)</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AndroidAsset>
  </ItemGroup>
</Project>